 ### 1.1 Lists
In Python, a list is the main data sturcture used to store a mutable sequence of elements. The sequence of data elements stored in the list need not to be of the same type.

To create a list, the data elemets need to be enclosed in [ ] and they need to be seperated by a comma. For example, the following code creates four data elements together which are of different types.

In [2]:
aList = ["John", 33, "Toronto", True]

In [3]:
aList

['John', 33, 'Toronto', True]

In [4]:
type(aList)

list

In [5]:
bin_colors=['Red', 'Green', 'Blue', 'Yellow']

### Tuples
The second data structure that can be used to store a collection is tuple, In contrast to list, tuples are immutable (read-only) data structures. Tuples consist of several elements surrounded by ( ).

Like lists, elements within a tuple can be different types. They are also allow complex data types to their elements. So there can be a tuple providing a way to create nested data structure. Capability to create nested data structures is especially useful in literative and recursive algorithms.

Following code demonstrate how to create tuples

In [6]:
bin_colors=('Red', 'Green', 'Blue', 'Yellow')
print(f"The second element of the tuple is {bin_colors[1]}")

The second element of the tuple is Green


In [8]:
print(f"The elemets after third element onwards are {bin_colors[2:]}")

The elemets after third element onwards are ('Blue', 'Yellow')


Let us define nested tuple data structure

In [9]:
nested_tuple = (1,2,(100,200,300),6)
print(f"The maximum value of the inner tuple {max(nested_tuple[2])}")

The maximum value of the inner tuple 300


### 1.2 Dictionary
To create a simple dictionary that assigns colors to various variables, the key-value pairs need to be enclosed in { }. For example, the following code creates a simple dictionary consisting of three key-value pairs.

In [10]:
bin_colors ={
    "Manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}

In [11]:
print(bin_colors)

{'Manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [12]:
bin_colors.get('approved_color')

'Green'

In [13]:
bin_colors['approved_color']

'Green'

In [14]:
bin_colors['approved_color']="Purple"

In [15]:
print(bin_colors)

{'Manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


### 1.3 Set
A set is defined as a collection of elements which can be of different types. The elemnts are enclosed with { }. For example, have a look at the following code block:

In [17]:
green = {'grass', 'leaves'}
print(green)

{'leaves', 'grass'}


In [18]:
yellow = {'dandelions', 'fire hydrant', 'leaves'}
red = {'fire hydrant', 'blood', 'rose', 'leaves'}

In [20]:
print(f"The union of yellow and red sets is {yellow|red}")

The union of yellow and red sets is {'dandelions', 'rose', 'leaves', 'fire hydrant', 'blood'}


In [21]:
print(f"The intersaction of yellow and red is {yellow&red}")

The intersaction of yellow and red is {'leaves', 'fire hydrant'}


### 1.4 DataFrame
DataFrame is a data structure used to store tabular data available in Python's pandas package. It is one of the most important data structures for algorithm and is used to process traditional structured data.
Now let us represent this by a DataFrame

A simple DataFrame can be operated by using the following code.

In [22]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]])
df.columns = ['id', 'name', 'age', 'decision']
print(df)

  id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True


### 1.4.1 Column Selection
The values of name and age columns are

In [23]:
df[['name', 'age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

The positioning of a comlumn is deterministic in a data frame. Fourth column can be retrieved by its position as follows:

In [24]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

### 1.4.2 Row Selection
Each row in DataFrame correspondsto data-point in our problem space. We need to perform row selection if we want to create a subset of the data elements we have in our problem space. This subset can be created by using one of two methods

By specifing their position By specifying a filter A subset of rows can be retrieved by its position as follows:

In [25]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

To create a subset by specifying the filter, we need to use one or more columns to define the selection criterion. For example, a subset data elemnts can be selected by this method as follows:

In [26]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

### 1.5 Matrix
A matrix is two-dimensional data structure with a fixed number of columns and rows. Each element of a matrix can be referred to by its column and the row.

In [27]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21,22,23], [31,32,33]])

In [29]:
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [30]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [31]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])